- name: Demo on Variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{URL}} is the URL"


- name: Demo on file Variables
  hosts: all
  vars_file:
    -sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
